### PR TITLE
Use Redux in React components.

### PR DESCRIPTION
**Pull request by XsidX**
For this PR I, 
  - Added event handlers to get user input from the addBook Form.
  - Added onClick event in the categories page to display the current status when the status button is clicked.
  - Used useDispatch to connect the addBook and check status button to the Redux store.

### CODE REVIEW

**Review by Bondok6 — CHANGES_REQUESTED** [review]
## Hi @XsidX 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Your project is professional ✅
- Your repo is professional ✅
- Great Job using Use store, actions, and reducers ✅
- Great Job Connecting React and Redux ✅
- No linter errors ✅ 

## Required Changes ♻️
- [ ] I noticed the MIT.md Link in your README is broken, So I suggest adding the `MIT.md` file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯




- [ ] Also the live demo link is broken, please fix or remove it, for now,👌💯 We should always be sure our repositories are documented professionally 🙏



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by XsidX** [comment]
Hello, I accidentally merged after making the corrections. I would have reverted the merge but that would open a new pull request. I hope this would not inconvenience the review. Have an awesome day☀.

**Comment by Nemwel-Boniface** [comment]
## Hello @XsidX              :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 



## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

- [ ] Kindly be keen not to merge PR before they are approved

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by XsidX** [comment]
@Nemwel-Boniface 
Thank you. Moving forward, I'll be careful.

**Pull request merged**
